import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { FeatureArticle } from '../src/feature-article';

const Home = () => {
  const { locale } = useRouter();
  return (
    <div>
      <Head>
        <title>Article</title>
        <meta name='Article' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FeatureArticle language={locale} />
    </div>
  );
};

export default Home;
